from ubuntu:jammy as build-comfyui
env PIP_EXTRA_INDEX_URL=https://download.pytorch.org/whl/cu124


run set -e \
        && apt update \
        && apt -y install git curl

run set -e \
	&& cd /opt \
        && git clone https://github.com/comfyanonymous/ComfyUI

run set -e \
	&& cd /opt/ComfyUI/custom_nodes \
        && git clone https://github.com/ltdrdata/ComfyUI-Manager
run set -e \
        && cd /opt/ComfyUI/custom_nodes \
        && git clone https://github.com/Fannovel16/comfyui_controlnet_aux
run set -e \
        && cd /opt/ComfyUI/custom_nodes \
        && git clone https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet
run set -e \
        && cd /opt/ComfyUI/custom_nodes \
        && git clone https://github.com/FizzleDorf/ComfyUI_FizzNodes
run set -e \
        && cd /opt/ComfyUI/custom_nodes \
        && git clone https://github.com/Kosinkadink/ComfyUI-AnimateDiff-Evolved
run set -e \
        && cd /opt/ComfyUI/custom_nodes \
        && git clone https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite
run set -e \
        && cd /opt/ComfyUI/custom_nodes \
        && git clone https://github.com/ZHO-ZHO-ZHO/ComfyUI-BRIA_AI-RMBG
run set -e \
        && cd /opt/ComfyUI/custom_nodes \
        && git clone https://github.com/cubiq/ComfyUI_InstantID
run set -e \
        && cd /opt/ComfyUI/custom_nodes \
        && git clone https://github.com/pythongosssss/ComfyUI-Custom-Scripts
run set -e \
        && cd /opt/ComfyUI/custom_nodes \
        && git clone https://github.com/cubiq/ComfyUI_IPAdapter_plus
run set -e \
        && cd /opt/ComfyUI/custom_nodes \
        && git clone https://github.com/AIGODLIKE/AIGODLIKE-COMFYUI-TRANSLATION
run set -e \
        && cd /opt/ComfyUI/custom_nodes \
        && git clone https://github.com/crystian/ComfyUI-Crystools
run set -e \
        && cd /opt/ComfyUI/custom_nodes \
        && git clone https://github.com/storyicon/comfyui_segment_anything
run set -e \
        && cd /opt/ComfyUI/custom_nodes \
        && git clone https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet
run set -e \
        && cd /opt/ComfyUI/custom_nodes \
        && git clone https://github.com/rgthree/rgthree-comfy
run set -e \
        && cd /opt/ComfyUI/custom_nodes \
        && git clone https://github.com/yolain/ComfyUI-Easy-Use
run set -e \
        && cd /opt/ComfyUI/custom_nodes \
        && git clone https://github.com/huchenlei/ComfyUI-layerdiffuse
run set -e \
        && cd /opt/ComfyUI/custom_nodes \
        && git clone https://github.com/kijai/ComfyUI-SUPIR
run set -e \
        && cd /opt/ComfyUI/custom_nodes \
        && git clone https://github.com/ltdrdata/ComfyUI-Inspire-Pack
run set -e \
        && cd /opt/ComfyUI/custom_nodes \
        && git clone https://github.com/city96/ComfyUI-GGUF


from build-comfyui as build-libs


run set -e \
	&& apt install -y wget

run set -e \
	&& cd /root \
        && apt install -y wget \
        && wget https://astral.sh/uv/install.sh \
        && bash install.sh \
	&& rm -rf install.sh

run . /root/.local/bin/env \ 
        && uv venv /opt/venv --python 3.11 --seed \
        && . /opt/venv/bin/activate


run set -e \
	&& . /root/.local/bin/env \
	&& . /opt/venv/bin/activate \
        && apt update \
        && apt -y remove python* \
        && apt -y autoremove

run echo "#!/usr/bin/bash" >> /opt/combine.sh \
        && echo "cat \$1 >> \$2" >> /opt/combine.sh \
        && echo "echo -e '\\\n' >> \$2" >> /opt/combine.sh

run set -e \
	&& . /root/.local/bin/env \
	&& . /opt/venv/bin/activate \
        && cd /opt \
        && uv pip install -r /opt/ComfyUI/requirements.txt

run set -e \
	&& . /root/.local/bin/env \
	&& . /opt/venv/bin/activate \
        && chmod +x /opt/combine.sh \
	&& apt install -y gcc make g++ \
        && find /opt/ComfyUI/custom_nodes|grep requirements.txt|grep -v /src/|grep -v /tests/|xargs -i /opt/combine.sh {} /opt/requirements.txt \
        && uv pip install async_timeout ultralytics!=8.2.5 diffusers -r /opt/requirements.txt \
        && uv pip install -r /opt/ComfyUI/custom_nodes/ComfyUI-GGUF/requirements.txt --upgrade

run set -e \
	&& . /root/.local/bin/env \
        && . /opt/venv/bin/activate \
        && cd /opt/ComfyUI/custom_nodes \
        && git clone https://github.com/XLabs-AI/x-flux-comfyui \
        && uv pip install -r /opt/ComfyUI/custom_nodes/x-flux-comfyui/requirements.txt \
        && cd /opt/ComfyUI/custom_nodes/x-flux-comfyui

run set -e \
	&& . /root/.local/bin/env \
        && . /opt/venv/bin/activate \
        && cd /opt/ComfyUI/custom_nodes \
        && git clone https://github.com/kijai/ComfyUI-segment-anything-2 \
        && uv pip install -r /opt/ComfyUI/custom_nodes/ComfyUI-segment-anything-2/requirements.txt \
        && cd /opt/ComfyUI/custom_nodes/ComfyUI-segment-anything-2

run set -e \
	&& . /root/.local/bin/env \
        && . /opt/venv/bin/activate \
        && cd /opt/ComfyUI/custom_nodes \
        && git clone https://github.com/kijai/ComfyUI-CogVideoXWrapper \
        && uv pip install -r /opt/ComfyUI/custom_nodes/ComfyUI-CogVideoXWrapper/requirements.txt \
        && cd /opt/ComfyUI/custom_nodes/ComfyUI-CogVideoXWrapper

run set -e \
	&& . /root/.local/bin/env \
        && . /opt/venv/bin/activate \
        && uv pip install xformers --upgrade


run set -e \
	&& . /root/.local/bin/env \
        && . /opt/venv/bin/activate \
        && cd /opt/ComfyUI/custom_nodes \
        && git clone https://github.com/kijai/ComfyUI-KJNodes \
        && uv pip install -r /opt/ComfyUI/custom_nodes/ComfyUI-KJNodes/requirements.txt \
        && cd /opt/ComfyUI/custom_nodes/ComfyUI-KJNodes

run set -e \
	&& . /root/.local/bin/env \
        && . /opt/venv/bin/activate \
        && cd /opt/ComfyUI/custom_nodes \
        && git clone https://github.com/cubiq/ComfyUI_essentials \
        && uv pip install -r /opt/ComfyUI/custom_nodes/ComfyUI_essentials/requirements.txt \
        && cd /opt/ComfyUI/custom_nodes/ComfyUI_essentials

run set -e \
	&& . /root/.local/bin/env \
        && . /opt/venv/bin/activate \
        && cd /opt/ComfyUI/custom_nodes \
        && git clone https://github.com/kadirnar/ComfyUI-YOLO \
        && uv pip install -r /opt/ComfyUI/custom_nodes/ComfyUI-YOLO/requirements.txt \
        && cd /opt/ComfyUI/custom_nodes/ComfyUI-YOLO

run set -e \
	&& . /root/.local/bin/env \
        && . /opt/venv/bin/activate \
        && cd /opt/ComfyUI/custom_nodes \
        && git clone https://github.com/Stability-AI/stability-ComfyUI-nodes \
        && uv pip install -r /opt/ComfyUI/custom_nodes/stability-ComfyUI-nodes/requirements.txt \
        && cd /opt/ComfyUI/custom_nodes/stability-ComfyUI-nodes

run set -e \
	&& . /root/.local/bin/env \
        && . /opt/venv/bin/activate \
        && cd /opt/ComfyUI/custom_nodes \
        && git clone https://github.com/jamesWalker55/comfyui-various

run set -e \
	&& . /root/.local/bin/env \
        && . /opt/venv/bin/activate \
        && cd /opt/ComfyUI/custom_nodes \
        && git clone https://github.com/SeaArtLab/ComfyUI-Long-CLIP \
        && cd /opt/ComfyUI/custom_nodes/ComfyUI-Long-CLIP

run set -e \
	&& . /root/.local/bin/env \
        && . /opt/venv/bin/activate \
        && cd /opt/ComfyUI/custom_nodes \
        && git clone https://github.com/Fannovel16/ComfyUI-Frame-Interpolation \
        && uv pip install -r /opt/ComfyUI/custom_nodes/ComfyUI-Frame-Interpolation/requirements-no-cupy.txt \
        && cd /opt/ComfyUI/custom_nodes/ComfyUI-Frame-Interpolation \
        && python install.py
run set -e \
	&& . /root/.local/bin/env \
        && . /opt/venv/bin/activate \
        && cd /opt/ComfyUI/custom_nodes \
        && git clone https://github.com/MofaAI/ComfyUI-Prompt-Translator \
        && cd /opt/ComfyUI/custom_nodes/ComfyUI-Prompt-Translator
run set -e \
	&& . /root/.local/bin/env \
        && . /opt/venv/bin/activate \
        && cd /opt/ComfyUI/custom_nodes \
        && git clone https://github.com/Gourieff/ComfyUI-ReActor \
        && uv pip install -r /opt/ComfyUI/custom_nodes/ComfyUI-ReActor/requirements.txt \
        && cd /opt/ComfyUI/custom_nodes/ComfyUI-ReActor \
        && python install.py
run set -e \
	&& . /root/.local/bin/env \
        && . /opt/venv/bin/activate \
        && cd /opt/ComfyUI/custom_nodes \
        && git clone https://github.com/AIGCTeam/ComfyUI_kkTranslator_nodes \
        && sed -i '/hashlib/d' /opt/ComfyUI/custom_nodes/ComfyUI_kkTranslator_nodes/requirements.txt \
        && sed -i '/random/d' /opt/ComfyUI/custom_nodes/ComfyUI_kkTranslator_nodes/requirements.txt \
        && sed -i '/json/d' /opt/ComfyUI/custom_nodes/ComfyUI_kkTranslator_nodes/requirements.txt \
        && uv pip install -r /opt/ComfyUI/custom_nodes/ComfyUI_kkTranslator_nodes/requirements.txt \
        && cd /opt/ComfyUI/custom_nodes/ComfyUI_kkTranslator_nodes
run set -e \
	&& . /root/.local/bin/env \
        && . /opt/venv/bin/activate \
        && cd /opt/ComfyUI/custom_nodes \
        && git clone https://github.com/kijai/ComfyUI-PyramidFlowWrapper \
        && uv pip install -r /opt/ComfyUI/custom_nodes/ComfyUI-PyramidFlowWrapper/requirements.txt \
        && cd /opt/ComfyUI/custom_nodes/ComfyUI-PyramidFlowWrapper

run set -e \
	&& . /root/.local/bin/env \
        && . /opt/venv/bin/activate \
        && cd /opt/ComfyUI/custom_nodes \
        && git clone https://github.com/pythongosssss/ComfyUI-WD14-Tagger \
        && uv pip install -r /opt/ComfyUI/custom_nodes/ComfyUI-WD14-Tagger/requirements.txt \
        && cd /opt/ComfyUI/custom_nodes/ComfyUI-WD14-Tagger

run set -e \
	&& . /root/.local/bin/env \
        && . /opt/venv/bin/activate \
        && cd /opt/ComfyUI/custom_nodes \
        && git clone https://github.com/Acly/comfyui-inpaint-nodes \
        && cd /opt/ComfyUI/custom_nodes/comfyui-inpaint-nodes

run set -e \
	&& . /root/.local/bin/env \
        && . /opt/venv/bin/activate \
        && cd /opt/ComfyUI/custom_nodes \
        && git clone https://github.com/chrisgoringe/cg-use-everywhere \
        && cd /opt/ComfyUI/custom_nodes/cg-use-everywhere
run set -e \
	&& . /root/.local/bin/env \
        && . /opt/venv/bin/activate \
        && cd /opt/ComfyUI/custom_nodes \
        && git clone https://github.com/chflame163/ComfyUI_CatVTON_Wrapper \
        && uv pip install -r /opt/ComfyUI/custom_nodes/ComfyUI_CatVTON_Wrapper/requirements.txt \
        && cd /opt/ComfyUI/custom_nodes/ComfyUI_CatVTON_Wrapper
run set -e \
	&& . /root/.local/bin/env \
        && . /opt/venv/bin/activate \
        && cd /opt/ComfyUI/custom_nodes \
        && git clone https://github.com/Fannovel16/ComfyUI-MotionDiff \
        && apt install libglfw3-dev libgles2-mesa-dev freeglut3-dev -y \
        && uv pip install -r /opt/ComfyUI/custom_nodes/ComfyUI-MotionDiff/requirements.txt \
        && cd /opt/ComfyUI/custom_nodes/ComfyUI-MotionDiff \
        && python install.py
run set -e \
	&& . /root/.local/bin/env \
        && . /opt/venv/bin/activate \
        && cd /opt/ComfyUI/custom_nodes \
        && git clone https://github.com/city96/SD-Latent-Interposer \
        && cd /opt/ComfyUI/custom_nodes/SD-Latent-Interposer

run set -e \
	&& . /root/.local/bin/env \
        && . /opt/venv/bin/activate \
        && cd /opt/ComfyUI/custom_nodes \
        && git clone https://github.com/ShmuelRonen/ComfyUI-FreeMemory \
        && cd /opt/ComfyUI/custom_nodes/ComfyUI-FreeMemory


run set -e \
	&& . /root/.local/bin/env \
        && . /opt/venv/bin/activate \
        && cd /opt/ComfyUI/custom_nodes \
        && git clone https://github.com/ltdrdata/ComfyUI-Impact-Pack \
        && uv pip install -r /opt/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/requirements.txt \
        && cd /opt/ComfyUI/custom_nodes/ComfyUI-Impact-Pack \
        && python install.py

run set -e \
	&& . /root/.local/bin/env \
        && . /opt/venv/bin/activate \
        && cd /opt/ComfyUI/custom_nodes \
        && git clone https://github.com/MinusZoneAI/ComfyUI-CogVideoX-MZ \
        && cd /opt/ComfyUI/custom_nodes/ComfyUI-CogVideoX-MZ

#run set -e \
#	&& . /root/.local/bin/env \
#        && . /opt/venv/bin/activate \
#        && cd /opt/ComfyUI/custom_nodes \
#        && git clone https://github.com/MzMaXaM/ComfyUi-MzMaXaM \
#        && cd /opt/ComfyUI/custom_nodes/ComfyUi-MzMaXaM

run set -e \
	&& . /root/.local/bin/env \
        && . /opt/venv/bin/activate \
        && cd /opt/ComfyUI/custom_nodes \
        && git clone https://github.com/stavsap/comfyui-ollama \
        && uv pip install -r /opt/ComfyUI/custom_nodes/comfyui-ollama/requirements.txt \
        && cd /opt/ComfyUI/custom_nodes/comfyui-ollama
run set -e \
	&& . /root/.local/bin/env \
        && . /opt/venv/bin/activate \
        && cd /opt/ComfyUI/custom_nodes \
        && git clone https://github.com/BlenderNeko/ComfyUI_ADV_CLIP_emb \
        && cd /opt/ComfyUI/custom_nodes/ComfyUI_ADV_CLIP_emb
run set -e \
	&& . /root/.local/bin/env \
        && . /opt/venv/bin/activate \
        && cd /opt/ComfyUI/custom_nodes \
        && git clone https://github.com/sleechengn/ComfyUI-TypeAux \
        && cd /opt/ComfyUI/custom_nodes/ComfyUI-TypeAux

run set -e \
	&& . /root/.local/bin/env \
        && . /opt/venv/bin/activate \
        && cd /opt/ComfyUI/custom_nodes \
        && git clone https://github.com/kaibioinfo/ComfyUI_AdvancedRefluxControl \
        && cd /opt/ComfyUI/custom_nodes/ComfyUI_AdvancedRefluxControl

run set -e \
	&& . /root/.local/bin/env \
        && . /opt/venv/bin/activate \
        && cd /opt/ComfyUI/custom_nodes \
        && git clone https://github.com/smthemex/ComfyUI_EchoMimic \
	&& uv pip install --no-deps facenet-pytorch \
        && uv pip install -r /opt/ComfyUI/custom_nodes/ComfyUI_EchoMimic/requirements.txt \
        && cd /opt/ComfyUI/custom_nodes/ComfyUI_EchoMimic
run set -e \
	&& . /root/.local/bin/env \
        && . /opt/venv/bin/activate \
        && cd /opt/ComfyUI/custom_nodes \
        && git clone https://github.com/adieyal/comfyui-dynamicprompts \
        && uv pip install -r /opt/ComfyUI/custom_nodes/comfyui-dynamicprompts/requirements.txt \
        && cd /opt/ComfyUI/custom_nodes/comfyui-dynamicprompts

run set -e \
	&& . /root/.local/bin/env \
        && . /opt/venv/bin/activate \
        && cd /opt/ComfyUI/custom_nodes \
        && git clone https://github.com/numz/Comfyui-FlowChain \
        && uv pip install -r /opt/ComfyUI/custom_nodes/Comfyui-FlowChain/requirements.txt \
        && uv pip install websocket websockets \
        && cd /opt/ComfyUI/custom_nodes/Comfyui-FlowChain
run set -e \
	&& . /root/.local/bin/env \
        && . /opt/venv/bin/activate \
        && cd /opt/ComfyUI/custom_nodes \
        && git clone https://github.com/kijai/ComfyUI-HunyuanVideoWrapper \
        && uv pip install -r /opt/ComfyUI/custom_nodes/ComfyUI-HunyuanVideoWrapper/requirements.txt \
        && cd /opt/ComfyUI/custom_nodes/ComfyUI-HunyuanVideoWrapper

run set -e \
	&& . /root/.local/bin/env \
        && . /opt/venv/bin/activate \
        && cd /opt/ComfyUI/custom_nodes \
        && git clone https://github.com/ShmuelRonen/ComfyUI-LatentSyncWrapper \
        && uv pip install -r /opt/ComfyUI/custom_nodes/ComfyUI-LatentSyncWrapper/requirements.txt \
        && cd /opt/ComfyUI/custom_nodes/ComfyUI-LatentSyncWrapper

run set -e \
	&& . /root/.local/bin/env \
        && . /opt/venv/bin/activate \
        && cd /opt/ComfyUI/custom_nodes \
        && uv pip install pip --upgrade \
        && git clone https://github.com/CY-CHENYUE/ComfyUI-Janus-Pro \
        && uv pip install -r /opt/ComfyUI/custom_nodes/ComfyUI-Janus-Pro/requirements.txt \
        && cd /opt/ComfyUI/custom_nodes/ComfyUI-Janus-Pro

run set -e \
	&& . /root/.local/bin/env \
        && . /opt/venv/bin/activate \
        && cd /opt/ComfyUI/custom_nodes \
        && git clone https://github.com/lgldlk/ComfyUI-FitDit

run set -e \
	&& . /root/.local/bin/env \
        && . /opt/venv/bin/activate \
        && cd /opt/ComfyUI/custom_nodes \
        && git clone https://github.com/Lightricks/ComfyUI-LTXVideo \
        && uv pip install -r /opt/ComfyUI/custom_nodes/ComfyUI-LTXVideo/requirements.txt \
        && cd /opt/ComfyUI/custom_nodes/ComfyUI-LTXVideo
run set -e \
	&& . /root/.local/bin/env \
        && . /opt/venv/bin/activate \
        && cd /opt/ComfyUI/custom_nodes \
        && git clone https://github.com/IamCreateAI/Ruyi-Models.git \
        && uv pip install -r /opt/ComfyUI/custom_nodes/Ruyi-Models/requirements.txt \
        && cd /opt/ComfyUI/custom_nodes/Ruyi-Models

run set -e \
	&& . /root/.local/bin/env \
        && . /opt/venv/bin/activate \
        && cd /opt/ComfyUI/custom_nodes \
        && git clone https://github.com/chengzeyi/Comfy-WaveSpeed \
        && cd /opt/ComfyUI/custom_nodes/Comfy-WaveSpeed
run set -e \
	&& . /root/.local/bin/env \
        && . /opt/venv/bin/activate \
        && cd /opt/ComfyUI/custom_nodes \
        && git clone https://github.com/welltop-cn/ComfyUI-TeaCache \
        && uv pip install -r /opt/ComfyUI/custom_nodes/ComfyUI-TeaCache/requirements.txt \
        && cd /opt/ComfyUI/custom_nodes/ComfyUI-TeaCache
run set -e \
	&& . /root/.local/bin/env \
        && . /opt/venv/bin/activate \
        && cd /opt/ComfyUI/custom_nodes \
        && git clone https://github.com/TTPlanetPig/Comfyui_TTP_Toolset
run set -e \
	&& . /root/.local/bin/env \
        && . /opt/venv/bin/activate \
        && cd /opt/ComfyUI/custom_nodes \
        && git clone https://github.com/smthemex/ComfyUI_StoryDiffusion \
        && uv pip install -r /opt/ComfyUI/custom_nodes/ComfyUI_StoryDiffusion/requirements.txt \
        && cd /opt/ComfyUI/custom_nodes/ComfyUI_StoryDiffusion

run set -e \
	&& . /root/.local/bin/env \
        && . /opt/venv/bin/activate \
        && cd /opt/ComfyUI/custom_nodes \
        && git clone https://github.com/yuvraj108c/ComfyUI_InvSR \
        && uv pip install -r /opt/ComfyUI/custom_nodes/ComfyUI_InvSR/requirements.txt \
        && cd /opt/ComfyUI/custom_nodes/ComfyUI_InvSR

run set -e \
	&& . /root/.local/bin/env \
        && . /opt/venv/bin/activate \
	&& cd /opt/ComfyUI/custom_nodes \
	&& git clone https://github.com/Tenney95/ComfyUI-NodeAligner \
	&& cd /opt/ComfyUI/custom_nodes/ComfyUI-NodeAligner
run set -e \
	&& . /root/.local/bin/env \
        && . /opt/venv/bin/activate \
        && cd /opt/ComfyUI/custom_nodes \
        && git clone https://github.com/smthemex/ComfyUI_Sonic \
        && uv pip install -r /opt/ComfyUI/custom_nodes/ComfyUI_Sonic/requirements.txt \
        && cd /opt/ComfyUI/custom_nodes/ComfyUI_Sonic

run set -e \
        && . /root/.local/bin/env \
        && . /opt/venv/bin/activate \
        && cd /opt/ComfyUI/custom_nodes \
        && git clone https://github.com/niknah/ComfyUI-F5-TTS \
	&& cd /opt/ComfyUI/custom_nodes/ComfyUI-F5-TTS \
	&& git submodule update --init --recursive \
        && uv pip install -r /opt/ComfyUI/custom_nodes/ComfyUI-F5-TTS/requirements.txt

run set -e \
        && . /root/.local/bin/env \
        && . /opt/venv/bin/activate \
        && cd /opt/ComfyUI/custom_nodes \
        && git clone https://github.com/kijai/ComfyUI-WanVideoWrapper \
        && uv pip install -r /opt/ComfyUI/custom_nodes/ComfyUI-WanVideoWrapper/requirements.txt \
        && cd /opt/ComfyUI/custom_nodes/ComfyUI-WanVideoWrapper

run set -e \
	&& . /root/.local/bin/env \
        && . /opt/venv/bin/activate \
        && uv pip install "numpy<2.0.0" --reinstall --upgrade
run set -e \
	&& . /root/.local/bin/env \
        && . /opt/venv/bin/activate \
        && uv pip install torchaudio
run set -e \
	&& rm -rf /opt/ComfyUI/models

from ubuntu:jammy as prod
env PIP_EXTRA_INDEX_URL=https://download.pytorch.org/whl/cu124

run set -e \
	&& apt update \
        && cd /root \
        && apt install -y wget \
        && wget https://astral.sh/uv/install.sh \
        && bash install.sh \
        && rm -rf install.sh

run set -e \
        && apt update \
        && apt remove python* \
        && apt autoremove \
        && apt -y install wget openssh-server curl git nginx fonts-noto-cjk-extra ffmpeg ttyd libglfw3-dev libgles2 \
        && sed -i 's/.*PermitRootLogin.*/PermitRootLogin yes/g' /etc/ssh/sshd_config \
        && mkdir /run/sshd \
        && chmod -R 700 /run/sshd \
        && chown -R root /run/sshd \
        && echo "root:root" | chpasswd \
        && curl -fsSL https://raw.githubusercontent.com/filebrowser/get/master/get.sh | bash \
        && mkdir /opt/filebrowser \
        && rm -rf /etc/nginx/sites-enabled/* \
        && apt autoremove

run set -e \
	&& apt install -y aria2 gcc make \
	&& cd /opt \
	&& aria2c --max-connection-per-server=10 --min-split-size=1M --max-concurrent-downloads=8 https://developer.download.nvidia.com/compute/cuda/12.6.3/local_installers/cuda_12.6.3_560.35.05_linux.run  \
        && chmod +x cuda_12.6.3_560.35.05_linux.run \
        && ./cuda_12.6.3_560.35.05_linux.run --silent --toolkit \
        && rm -rf cuda_12.6.3_560.35.05_linux.run

env CUDA_HOME=/usr/local/cuda-12.6

copy --from=build-libs /opt/venv /opt/venv
copy --from=build-libs /opt/ComfyUI /opt/ComfyUI
copy --from=build-libs /root/.local /root/.local

run set -e \
	&& apt install -y g++ language-pack-zh-hans \
	&& locale-gen zh_CN.UTF-8 \
	&& update-locale LANG=zh_CN.UTF-8

copy ./installer /opt/installer

add ./ComfyUI /etc/nginx/sites-enabled/

# setup and initialize
copy ./docker-entrypoint.sh /
run chmod +x /docker-entrypoint.sh
entrypoint ["/docker-entrypoint.sh"]
cmd []

workdir /opt/ComfyUI

env ROOT_PASSWORD=root

volume /root
volume /root/.local
volume /opt/installer
volume /opt/ComfyUI
volume /opt/ComfyUI/models
volume /opt/ComfyUI/custom_nodes/comfyui_controlnet_aux/ckpts
volume /opt/venv
volume /opt/ComfyUI/custom_nodes/ComfyUI-WD14-Tagger/models
volume /opt/ComfyUI/user
volume /opt/ComfyUI/custom_nodes/ComfyUI-Frame-Interpolation/ckpts
volume /opt/ComfyUI/custom_nodes/ComfyUI-LatentSyncWrapper/checkpoints
