FROM ubuntu:jammy AS build-comfyui
ENV PIP_EXTRA_INDEX_URL=https://download.pytorch.org/whl/cu124

COPY ./stage-comfyui.sh /opt/
RUN /usr/bin/bash /opt/stage-comfyui.sh
CMD ["/usr/bin/bash"]




FROM ubuntu:jammy AS build-libs
ENV PIP_EXTRA_INDEX_URL=https://download.pytorch.org/whl/cu124

COPY --from=build-comfyui /opt/ComfyUI /opt/ComfyUI
COPY ./combine.sh /opt/combine.sh

COPY ./stage-libs-apt.sh /opt/
RUN /usr/bin/bash /opt/stage-libs-apt.sh

COPY ./stage-libs-comfyui.sh /opt/
RUN /usr/bin/bash /opt/stage-libs-comfyui.sh

COPY ./stage-libs-ext.sh /opt/
RUN /usr/bin/bash /opt/stage-libs-ext.sh

COPY ./stage-plugin-x-flux-comfyui.sh /opt/
RUN /usr/bin/bash /opt/stage-plugin-x-flux-comfyui.sh

COPY ./stage-plugin-segment-anything2.sh /opt/
RUN /usr/bin/bash /opt/stage-plugin-segment-anything2.sh

#COPY ./stage-plugin-ComfyUI-MimicMotion.sh /opt/
#RUN /usr/bin/bash /opt/stage-plugin-ComfyUI-MimicMotion.sh

COPY ./stage-plugin-ComfyUI-CogVideoXWrapper.sh /opt/
RUN /usr/bin/bash /opt/stage-plugin-ComfyUI-CogVideoXWrapper.sh

COPY ./stage-fix-xformers.sh /opt/
RUN /usr/bin/bash /opt/stage-fix-xformers.sh

COPY ./stage-plugin-ComfyUI-KJNodes.sh /opt/
RUN /usr/bin/bash /opt/stage-plugin-ComfyUI-KJNodes.sh

COPY ./stage-plugin-ComfyUI_essentials.sh /opt/
RUN /usr/bin/bash /opt/stage-plugin-ComfyUI_essentials.sh

COPY ./stage-plugin-ComfyUI-YOLO.sh /opt/
RUN /usr/bin/bash /opt/stage-plugin-ComfyUI-YOLO.sh

COPY ./stage-plugin-stability-ComfyUI-nodes.sh /opt/
RUN /usr/bin/bash /opt/stage-plugin-stability-ComfyUI-nodes.sh

COPY ./stage-plugin-comfyui-various.sh /opt/
RUN /usr/bin/bash /opt/stage-plugin-comfyui-various.sh

COPY ./stage-plugin-ComfyUI-Long-CLIP.sh /opt/
RUN /usr/bin/sh /opt/stage-plugin-ComfyUI-Long-CLIP.sh

COPY ./stage-plugin-ComfyUI-Frame-Interpolation.sh /opt/
RUN /usr/bin/sh /opt/stage-plugin-ComfyUI-Frame-Interpolation.sh

COPY ./stage-plugin-ComfyUI-Prompt-Translator.sh /opt/
RUN /usr/bin/sh /opt/stage-plugin-ComfyUI-Prompt-Translator.sh

COPY ./stage-plugin-comfyui-reactor-node.sh /opt/
RUN /usr/bin/sh /opt/stage-plugin-comfyui-reactor-node.sh

COPY ./stage-plugin-ComfyUI_kkTranslator_nodes.sh /opt/
RUN /usr/bin/sh /opt/stage-plugin-ComfyUI_kkTranslator_nodes.sh

COPY ./stage-plugin-ComfyUI-PyramidFlowWrapper.sh /opt/
RUN /usr/bin/sh /opt/stage-plugin-ComfyUI-PyramidFlowWrapper.sh

COPY ./stage-plugin-ComfyUI-WD14-Tagger.sh /opt/
RUN /usr/bin/sh /opt/stage-plugin-ComfyUI-WD14-Tagger.sh

COPY ./stage-plugin-comfyui-inpaint-nodes.sh /opt/
RUN /usr/bin/sh /opt/stage-plugin-comfyui-inpaint-nodes.sh

COPY ./stage-plugin-cg-use-everywhere.sh /opt/
RUN /usr/bin/sh /opt/stage-plugin-cg-use-everywhere.sh

COPY ./stage-plugin-ComfyUI_CatVTON_Wrapper.sh /opt/
RUN /usr/bin/sh /opt/stage-plugin-ComfyUI_CatVTON_Wrapper.sh

COPY ./stage-plugin-ComfyUI-MotionDiff.sh /opt/
RUN /usr/bin/sh /opt/stage-plugin-ComfyUI-MotionDiff.sh

COPY ./stage-plugin-SD-Latent-Interposer.sh /opt/
RUN /usr/bin/sh /opt/stage-plugin-SD-Latent-Interposer.sh

COPY ./stage-plugin-ComfyUI-FreeMemory.sh /opt/
RUN /usr/bin/sh /opt/stage-plugin-ComfyUI-FreeMemory.sh

COPY ./stage-plugin-ComfyUI-Impact-Pack.sh /opt/
RUN /usr/bin/sh /opt/stage-plugin-ComfyUI-Impact-Pack.sh

COPY ./stage-plugin-ComfyUI-CogVideoX-MZ.sh /opt/
RUN /usr/bin/sh /opt/stage-plugin-ComfyUI-CogVideoX-MZ.sh

COPY ./stage-plugin-ComfyUI-MzMaXaM.sh /opt/
RUN /usr/bin/sh /opt/stage-plugin-ComfyUI-MzMaXaM.sh

COPY ./stage-plugin-comfyui-ollama.sh /opt/
RUN /usr/bin/sh /opt/stage-plugin-comfyui-ollama.sh

COPY ./stage-plugin-ComfyUI_ADV_CLIP_emb.sh /opt/
RUN /usr/bin/sh /opt/stage-plugin-ComfyUI_ADV_CLIP_emb.sh

COPY ./stage-plugin-CogVideoX-Fun.sh /opt/
RUN /usr/bin/sh /opt/stage-plugin-CogVideoX-Fun.sh

COPY ./stage-plugin-OmniGen-ComfyUI.sh /opt/
RUN /usr/bin/sh /opt/stage-plugin-OmniGen-ComfyUI.sh

COPY ./stage-plugin-ComfyUI-TypeAux.sh /opt/
RUN /usr/bin/sh /opt/stage-plugin-ComfyUI-TypeAux.sh

COPY ./stage-plugin-ComfyUI_AdvancedRefluxControl.sh /opt/
RUN /usr/bin/sh /opt/stage-plugin-ComfyUI_AdvancedRefluxControl.sh

COPY ./stage-plugin-ComfyUI_EchoMimic.sh /opt/
RUN /usr/bin/sh /opt/stage-plugin-ComfyUI_EchoMimic.sh

COPY ./stage-plugin-comfyui-dynamicprompts.sh /opt/
RUN /usr/bin/sh /opt/stage-plugin-comfyui-dynamicprompts.sh

COPY ./stage-plugin-Comfyui-FlowChain.sh /opt/
RUN /usr/bin/sh /opt/stage-plugin-Comfyui-FlowChain.sh
#COPY ./stage-plugin-ComfyUI-LTXVideo.sh /opt/
#RUN /usr/bin/sh /opt/stage-plugin-ComfyUI-LTXVideo.sh

COPY ./stage-plugin-ComfyUI-HunyuanVideoWrapper.sh /opt/
RUN /usr/bin/sh /opt/stage-plugin-ComfyUI-HunyuanVideoWrapper.sh

COPY ./stage-fix-numpy.sh /opt/
RUN /usr/bin/sh /opt/stage-fix-numpy.sh

COPY ./stage-fix-torchaudio.sh /opt/
RUN /usr/bin/sh /opt/stage-fix-torchaudio.sh

#COPY ./stage-cuda-prepare-install.sh /opt/
#RUN /usr/bin/sh /opt/stage-cuda-prepare-install.sh
#COPY ./stage-fix-SageAttention.sh /opt/
#RUN /usr/bin/sh /opt/stage-fix-SageAttention.sh

CMD ["/usr/bin/bash"]



FROM ubuntu:jammy AS prod
ENV PIP_EXTRA_INDEX_URL=https://download.pytorch.org/whl/cu124

ADD ./settings.sh /opt/
RUN chmod +x /opt/settings.sh && /opt/settings.sh && rm -rf /opt/settings.sh

ADD ./settings-cuda.sh /opt/
RUN chmod +x /opt/settings-cuda.sh && /opt/settings-cuda.sh && rm -rf /opt/settings-cuda.sh

ENV CUDA_HOME=/usr/local/cuda-12.6

COPY --from=build-libs /usr/local/lib/python3.11/dist-packages /usr/local/lib/python3.11/dist-packages
COPY --from=build-libs /opt/ComfyUI /opt/ComfyUI

RUN mkdir -p /opt/installer
ADD ./settings-sageattention.sh /opt/installer/

ADD ./ComfyUI /etc/nginx/sites-enabled/

# setup and initialize
COPY ./init.sh /
RUN chmod +x /init.sh
COPY ./install.sh /
RUN chmod +x /install.sh

ENTRYPOINT ["/init.sh"]
CMD []

WORKDIR /opt/ComfyUI

ENV ROOT_PASSWORD=root

VOLUME /opt/ComfyUI
VOLUME /opt/ComfyUI/models
VOLUME /opt/ComfyUI/custom_nodes/comfyui_controlnet_aux/ckpts
#VOLUME /opt/ComfyUI/custom_nodes/ComfyUI-MimicMotion/models
VOLUME /usr/local/lib/python3.11/dist-packages
VOLUME /opt/ComfyUI/custom_nodes/ComfyUI-WD14-Tagger/models
VOLUME /opt/ComfyUI/user
VOLUME /opt/ComfyUI/custom_nodes/ComfyUI-Frame-Interpolation/ckpts
